import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from 'next-themes'
import { Toaster } from "sonner";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${inter.className}`}>
        <ThemeProvider attribute="class">
          <main>
            <>
             {children}
             </>
             <NextTopLoader
              color="var(--color-primary)"
              showSpinner={false}
             
             />
             <Toaster position="bottom-left" richColors closeButton={true} pauseWhenPageIsHidden={true} />

          </main>
         
        </ThemeProvider>
      </body>
    </html>
  );
}